name: build

on:
  push:
    branches:
      - jevinskie/source/feat/flac
  repository_dispatch:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout www
        uses: actions/checkout@v4.1.1
        with:
          ref: jevinskie/source/feat/flac

      - name: Checkout toolkit
        uses: actions/checkout@v4.1.1
        with:
          repository: jevinskie/roc-toolkit
          ref: jevinskie/feat/flac
          path: roc-toolkit

      - name: Pull docker image
        run: docker pull rocstreaming/env-sphinx

      - name: Build documentation
        run: |
          docker run --rm -t -u "${UID}" -v "$(pwd)":/opt/roc -w /opt/roc rocstreaming/env-sphinx \
              scons -C roc-toolkit --enable-sphinx --enable-doxygen docs
          cp -av roc-toolkit/docs/html www/toolkit

      - name: Publish web-site
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: jevinskie/content/feat/flac
          folder: www
          single-commit: true
